### ISSUE TITLE
I think only should load new messages if the user scroll down on top to refresh.

### ISSUE THREAD

**Issue by bitcoinuser** [plasma-social/plasma#169]
Hi,

I think only should load new messages if the user scroll down on top to refresh.

Why? If I'm on middle of the feed and I click on a note to see the replies than I click android back button, it looses the feed position if new messages are loaded.

Thanks.

**Comment by bitcoinuser** [comment]
> Why? If I'm on middle of the feed and I click on a note to see the replies than I click android back button, it looses the feed position if new messages are loaded.

The reason was this and it's fixed.

**Comment by jmateoac** [comment]
> > Why? If I'm on middle of the feed and I click on a note to see the replies than I click android back button, it looses the feed position if new messages are loaded.
> 
> The reason was this and it's fixed.

Thanks for going through the issues and closing them 🙏🏽
