### ISSUE TITLE
If I'm on Replies tab and click on feed bottom button, shouldn't jump to Following tab

### ISSUE THREAD

**Issue by bitcoinuser** [plasma-social/plasma#174]
Hi.

I think If I'm on Replies tab and click on feed bottom button, shouldn't jump to Following tab. 

Thanks.

**Comment by jmateoac** [comment]
* When tapping on a feed tab (on the top), we should scroll to the top of the feed.
* When tapping a bottom bar icon, we should scroll the current feed to the top.

**Comment by bitcoinuser** [comment]
> * When tapping on a feed tab (on the top), we should scroll to the top of the feed.
> * When tapping a bottom bar icon, we should scroll the current feed to the top.

Yes
